export const DESTINATION_PAGE_CONTENT = {
  hero_title: "Explore East Africa's Most Remarkable Destinations",
  hero_subtitle:
    "From Rwanda's misty gorilla forests to Uganda's primate strongholds and Eastern DRC's volcanic frontiers, discover the places that define a Virunga Expedition journey.",
  featured_heading: "Featured Destination Packages",
  guides_heading: "Destination Guides",
};

export const DESTINATION_GUIDES = [
  {
    country: "rwanda",
    title: "Rwanda",
    intro:
      "Rwanda offers some of Africa's most accessible and well-protected wildlife experiences, combining premium gorilla trekking with rainforest primates, classic safari, and polished logistics.",
    content_markdown:
      "Rwanda is ideal for travelers who want high-quality conservation travel with efficient transfers and excellent guiding. Within a relatively compact circuit, you can move from Volcanoes National Park for mountain gorillas and golden monkeys, to Nyungwe for chimpanzees and canopy walks, then east to Akagera for Big Five safari.\n\nThe country is especially strong for first-time safari travelers, photographers who need reliable logistics, and couples or families who want wildlife without excessively long road days. Kigali also works well as a soft landing, with cultural visits and city touring before or after the parks.",
    key_points: [
      "Best known for luxury gorilla trekking in Volcanoes National Park",
      "Easy to combine gorillas, chimps, canopy walk, and Big Five safari",
      "Shorter driving times than many regional circuits",
      "Strong conservation model with polished tourism infrastructure",
    ],
    cta_label: "Explore Rwanda Itineraries",
    cta_link: "/itineraries",
    is_active: true,
    display_order: 1,
  },
  {
    country: "uganda",
    title: "Uganda",
    intro:
      "Uganda delivers outstanding primate encounters with broader wilderness variety, making it a strong choice for travelers who want value, biodiversity, and longer overland safari circuits.",
    content_markdown:
      "Uganda is often chosen by travelers who want to combine gorilla trekking with classic safari landscapes and a wider range of primate experiences. Bwindi is world-famous for mountain gorillas, while Kibale offers some of East Africa's strongest chimpanzee tracking. Queen Elizabeth adds boat safaris, savannah wildlife, and the chance of seeing tree-climbing lions.\n\nCompared with Rwanda, Uganda often suits travelers who prefer longer, more diverse itineraries and are comfortable with bigger overland journeys. It is especially strong for return safari guests, wildlife enthusiasts, and travelers balancing permit cost with experience depth.",
    key_points: [
      "Home to Bwindi, one of the world's most important gorilla habitats",
      "Excellent chimpanzee experiences in Kibale Forest",
      "Combines primates with savannah parks like Queen Elizabeth",
      "Often offers strong value for multi-day primate and safari trips",
    ],
    cta_label: "Plan a Uganda Journey",
    cta_link: "/contact",
    is_active: true,
    display_order: 2,
  },
  {
    country: "drc",
    title: "Eastern DRC",
    intro:
      "Eastern DRC is the region for high-adventure conservation travel, combining dramatic volcanoes, deep history, and raw landscapes that feel far more remote than the standard East Africa circuit.",
    content_markdown:
      "Eastern DRC appeals to adventurous travelers looking for something more rugged and uncommon. Virunga National Park is Africa's oldest national park and remains one of the continent's most compelling conservation stories. Nearby Mount Nyiragongo delivers one of the world's most dramatic volcano hikes, with an overnight crater-rim experience overlooking the lava lake.\n\nThis destination is best for travelers who understand the need for close operational planning, flexible logistics, and security-led decision making. When conditions align, it offers an experience that is more intense, more remote, and unlike anywhere else in the region.",
    key_points: [
      "Virunga National Park offers rare, conservation-centered adventure travel",
      "Nyiragongo is one of the world's most iconic volcano hikes",
      "Best suited to flexible travelers comfortable with expedition logistics",
      "Pairs naturally with regional Rwanda or Uganda extensions when feasible",
    ],
    cta_label: "Request a DRC Expedition Plan",
    cta_link: "/contact",
    is_active: true,
    display_order: 3,
  },
];

export const DESTINATION_PACKAGES = [
  {
    id: "rwanda-volcanoes",
    country: "rwanda",
    title: "Volcanoes National Park",
    subtitle: "Mountain gorillas and golden monkeys",
    location: "Northwestern Rwanda",
    image_key: "gorilla",
    image_url: null,
    description: "Rwanda's flagship wildlife destination for gorilla trekking, golden monkeys, and volcano hikes.",
    highlights: ["Mountain Gorilla Trekking", "Golden Monkey Tracking", "Dian Fossey Tomb Hike"],
    badges: ["2 hours from Kigali", "$1,500 Gorilla Permit", "12 Habituated Gorilla Families"],
    link: "/tours/gorilla-trekking",
    display_order: 1,
    is_active: true,
  },
  {
    id: "rwanda-nyungwe",
    country: "rwanda",
    title: "Nyungwe Forest National Park",
    subtitle: "Ancient rainforest and primate hotspot",
    location: "Southwestern Rwanda",
    image_key: "forest",
    image_url: null,
    description: "UNESCO-listed montane rainforest with chimpanzees, canopy walkway, and exceptional biodiversity.",
    highlights: ["Chimpanzee Trekking", "Canopy Walkway", "Colobus Monkey Tracking"],
    badges: ["UNESCO Site", "13 Primate Species", "310+ Bird Species"],
    link: "/tours/chimpanzee",
    display_order: 2,
    is_active: true,
  },
  {
    id: "rwanda-akagera",
    country: "rwanda",
    title: "Akagera National Park",
    subtitle: "Rwanda's Big Five safari park",
    location: "Eastern Rwanda",
    image_key: "safari",
    image_url: null,
    description: "Classic savannah safari destination with game drives, boat safaris, and major conservation success.",
    highlights: ["Big Five Game Drives", "Lake Ihema Boat Safari", "Night Game Drives"],
    badges: ["1,122 sq km", "Big Five", "2.5 hours from Kigali"],
    link: "/tours/akagera-safari",
    display_order: 3,
    is_active: true,
  },
  {
    id: "rwanda-lake-kivu",
    country: "rwanda",
    title: "Lake Kivu",
    subtitle: "Relaxation and lakeside adventure",
    location: "Western Rwanda",
    image_key: "lake",
    image_url: null,
    description: "Rwanda's Riviera with scenic towns, island exploration, water sports, and Congo Nile Trail access.",
    highlights: ["Sunset Cruises", "Kayaking & Paddleboarding", "Island Tours"],
    badges: ["Africa's 6th Largest Lake", "Safe Swimming", "Great Post-Trek Add-On"],
    link: "/itineraries",
    display_order: 4,
    is_active: true,
  },
  {
    id: "rwanda-kigali",
    country: "rwanda",
    title: "Kigali City",
    subtitle: "Cultural and historical gateway",
    location: "Kigali",
    image_key: "city",
    image_url: null,
    description: "Modern, clean capital city with powerful history, vibrant arts, markets, and culinary experiences.",
    highlights: ["Kigali Genocide Memorial", "Inema Arts Center", "Kimironko Market"],
    badges: ["Safest African Capitals", "Ideal Arrival/Departure Base", "Half/Full Day Tours"],
    link: "/tours/kigali-city-tour",
    display_order: 5,
    is_active: true,
  },
  {
    id: "uganda-bwindi",
    country: "uganda",
    title: "Bwindi Impenetrable Forest",
    subtitle: "Half of world's mountain gorillas",
    location: "Southwestern Uganda",
    image_key: "gorilla",
    image_url: null,
    description: "UNESCO-protected rainforest and the most important gorilla conservation area in the world.",
    highlights: ["Gorilla Trekking", "Gorilla Habituation Experience", "Batwa Cultural Visits"],
    badges: ["19 Habituated Families", "$800 Gorilla Permit", "4 Trekking Sectors"],
    link: "/itineraries",
    display_order: 6,
    is_active: true,
  },
  {
    id: "uganda-queen-elizabeth",
    country: "uganda",
    title: "Queen Elizabeth National Park",
    subtitle: "Savannah wildlife and tree-climbing lions",
    location: "Western Uganda",
    image_key: "safari",
    image_url: null,
    description: "Diverse ecosystems with classic safaris, Kazinga Channel boat trips, and Ishasha lion sightings.",
    highlights: ["Kazinga Channel Boat Safari", "Tree-Climbing Lions", "Savannah Game Drives"],
    badges: ["Uganda's Most Visited Park", "Birding Paradise", "Excellent Multi-Day Circuits"],
    link: "/itineraries",
    display_order: 7,
    is_active: true,
  },
  {
    id: "uganda-kibale",
    country: "uganda",
    title: "Kibale Forest National Park",
    subtitle: "Primate capital of East Africa",
    location: "Western Uganda",
    image_key: "forest",
    image_url: null,
    description: "One of Africa's best chimpanzee destinations with rich primate diversity and guided forest experiences.",
    highlights: ["Chimpanzee Trekking", "Bigodi Wetland Walk", "Primate Viewing"],
    badges: ["High Chimp Sighting Rate", "13 Primate Species", "Great Combo with Queen Elizabeth"],
    link: "/itineraries",
    display_order: 8,
    is_active: true,
  },
  {
    id: "drc-virunga",
    country: "drc",
    title: "Virunga National Park",
    subtitle: "Africa's oldest national park",
    location: "Eastern DRC",
    image_key: "virunga-mountains",
    image_url: null,
    description: "Dramatic landscapes, gorilla trekking, and deep conservation significance in a unique adventure setting.",
    highlights: ["Mountain Gorilla Trekking", "Virunga Conservation Experience", "Scenic Volcanic Terrain"],
    badges: ["UNESCO World Heritage", "$400 Gorilla Permit", "Armed Ranger Support"],
    link: "/itineraries",
    display_order: 9,
    is_active: true,
  },
  {
    id: "drc-nyiragongo",
    country: "drc",
    title: "Mount Nyiragongo",
    subtitle: "Overnight lava lake summit",
    location: "Eastern DRC",
    image_key: "volcano",
    image_url: null,
    description: "One of the world's most dramatic active volcano experiences with overnight cabins on the crater rim.",
    highlights: ["Volcano Hike", "Lava Lake Views", "Crater-Rim Overnight"],
    badges: ["Active Volcano", "High-Adventure", "Unique East Africa Experience"],
    link: "/itineraries",
    display_order: 10,
    is_active: true,
  },
];

export const DESTINATION_GUIDES_BY_COUNTRY = Object.fromEntries(
  DESTINATION_GUIDES.map((guide) => [guide.country, guide]),
);
